### ISSUE TITLE
推流密码

### ISSUE THREAD

**Issue by aaaayuan** [pili-engineering/wxapp-live-demo#5]
推流动态密码是什么

**Comment by disoul** [comment]
您好，我们发布的小程序因为政策原因限制了用户推流，可以在[这里](https://support.qiniu.com/tickets/new?space=%E7%9B%B4%E6%92%AD%E4%BA%91&category=%E5%85%B6%E4%BB%96%E8%AE%BE%E5%A4%87%E6%8E%A8%E6%B5%81%E9%97%AE%E9%A2%98)提交工单留下您的联系方式获取临时的推流密码。   
另外，本仓库 demo 代码中是没有推流密码相关逻辑的。
